### ISSUE TITLE
[JOSS Review] Install missing dependencies and error hidden in logs

### ISSUE THREAD

**Issue by aquilesC** [ANP-Granular/ParticleTracking#74]
**Describe the bug**
Following the installation steps in the documentation, the program does not run because some dependencies are missing.
The first one I encountered was PyTorch, but there are others missing. 

This happened after install RodTracker, and persisted after installing ParticleDetection. 

The error is logged but hidden, so it took me a while to find out what was going on. It would be convinient, perhaps, to find another way of dealing with these type of exceptions. 

JOSS Issue: https://github.com/openjournals/joss-reviews/issues/5986

**Comment by dmitrypuzyrev** [comment]
Dear @aquilesC,
I have notified our main developer, @a-niem , about the issues. He will be available from this Thursday, 30.11, and reply you as soon as possible. Meanwhile, could you please provide the additional information: 

1. From which branch did you install the packages
2. What system/OS do you have
3. It would be important that you provide the logfile which you have obtained

Many thanks!

**Comment by dmitrypuzyrev** [comment]
Dear @aquilesC,

the installation problems are already resolved in the `develop` branch. 
There, the installation process should go without problems, if it is done from the fresh virtual environment created with `venv`.
We will update the `joss-paper` branch and software documentation accordingly in the beginning of the next week.

Thank you for pointing our the bug.

**Comment by dmitrypuzyrev** [comment]
Dear @aquilesC,

the `master` as well as `joss-paper` branches are updated with the latest program version.
The installation problems you've encountered should have been resolved and the documentation updated.
Please let us know if there are any other issues.

**Comment by mhubii** [comment]
https://github.com/openjournals/joss-reviews/issues/5986

**Comment by a-niem** [comment]
A popup window has been added that warns users when unhandled exceptions occur during program execution. It will also be shown when `ImportErrors` occur during startup of the application, e.g. when libraries are missing as described above.
