### ISSUE TITLE
[JOSS Review] Couldn't find the trained RCNN for the example data

### ISSUE THREAD

**Issue by aquilesC** [ANP-Granular/ParticleTracking#75]
**Describe the bug**
The documentation states that "With this app comes a trained RCNN for detecting rods from the example dataset" but couldn't find it. 

A potential improvement: Instead of leaving the example data within the software, move it outside, to the root folder, or perhaps make it avilable independently on Zenodo.  

JOSS Issue: https://github.com/openjournals/joss-reviews/issues/5986

**Comment by mhubii** [comment]
hi both, just seeing this issue. It should not be necessary to download manually. Please use torch hub, refer #85. Please further consider publishing as asset in release (although this is not necessary)

**Comment by mhubii** [comment]
https://github.com/openjournals/joss-reviews/issues/5986

**Comment by a-niem** [comment]
A button has been added to the `Detection` tab that downloads the example model from Zenodo. 
The other example data won't be moved for now.
