### ISSUE TITLE
[JOSS Review] Publish on pypi

### ISSUE THREAD

**Issue by mhubii** [ANP-Granular/ParticleTracking#78]
Would it be possible to make this pip-installable (https://pypi.org/)?

Since only interpretable code is used, this should be possible. Please advise if not @a-niem 

Please further consider adding a git action to publish on PR, refer https://github.com/marketplace/actions/pypi-publish

**Comment by a-niem** [comment]
Yes, we can publish it to PyPI and thereby make it pip-installable by name.
My suggestion is to publish the software in its current state as two separate packages.

> Please further consider adding a git action to publish on PR [...]

With the above in place we should definitly add automated publishing on certain PRs.

**Comment by mhubii** [comment]
okay, great! Really up to you how you publish, but I think that would enhance the software greatly!

**Comment by mhubii** [comment]
https://github.com/openjournals/joss-reviews/issues/5986

**Comment by a-niem** [comment]
This is fixed with [eb3af87](https://github.com/ANP-Granular/ParticleTracking/commit/eb3af8773041c0a60084a6932267bff80af6a20b).
