### ISSUE TITLE
[JOSS Review] Sort imports re-factor

### ISSUE THREAD

**Issue by mhubii** [ANP-Granular/ParticleTracking#80]
Hope this is not too OCD, but consider sorting imports, using e.g. https://pycqa.github.io/isort/, which has e.g. a visual studio code plugin https://marketplace.visualstudio.com/items?itemName=ms-python.isort

See e.g. this file https://github.com/ANP-Granular/ParticleTracking/blob/c946deafaffc8283fe4468d54604eb98765b9e8d/RodTracker/src/RodTracker/ui/reconstruction.py#L18

**Comment by mhubii** [comment]
https://github.com/openjournals/joss-reviews/issues/5986

**Comment by a-niem** [comment]
Imports have been sorted, and a workflow has been updated to verify adherence in new commits.
