### ISSUE TITLE
Rod Tracker - Change select mode of Load Images dialogue

### ISSUE THREAD

**Issue by merrygoat** [ANP-Granular/ParticleTracking#88]
When using the "Load Images" button in Rod Tracker, the open file dialogue opens in file select mode. This is confusing because it only lets me select one file but then on loading it loads the whole folder of files.

Suggestion: Either allow selection of multiple files and load only the selected files or allow selection of a folder and open all images in that folder. 

Since you use QFileDialog, I think  either of these options could be achieved using the setFileMode() function of the QFileDialog widget.

**Comment by a-niem** [comment]
The mode has been adjusted as requested.
Now a directory must be selected, and the first file contained in it will be displayed immediately. When moving into a directory in the picker dialog the relevant files contained in it are displayed. This behavior has been adopted to the position data selection, too. 

This however, leads to situation where users cannot confirm the selection when (accidentally) selecting one of the files in the folder that they would like to open.

Unfortunately, the in my opinion optimal solution of displaying the contained files but having them non-interactive, was not possible to achieve.

@dmitrypuzyrev and @merrygoat It would be great, if you could test out this new behavior in the `develop` branch and let me know about your opinions on it.

**Comment by merrygoat** [comment]
Initially I did try to click on an individual image and it does nothing and then when you look more closely, the select box is greyed out, the dialogue title is "Open a Folder" and the file type selector says "directory" in it so I think this behaviour is quite clear.

**Comment by a-niem** [comment]
Ok, then we keep it this way.
