### ISSUE TITLE
More than one error dialog can be shown at once

### ISSUE THREAD

**Issue by merrygoat** [ANP-Granular/ParticleTracking#92]
**Describe the bug**
An unhandled exception opens an error dialog. Because the dialog is not modal, you can continue interacting with the GUI and repeat the same operation causing a cascade of error dialog boxes to appear.

**Expected behaviour**
If the exception is non fatal and it is not required to inform the user it should be logged as a warning not with a dialog.

If it is required to inform the user then the error dialog should be modal to prevent further interaction with the GUI.

**Comment by a-niem** [comment]
The error dialogue has been switched to be modal  (see  06970c3). It now prevents the user from repeating the same operation without having to acknowledge the error prior to that.

There is however still the possibility that multiple of these dialogues are shown. This might occur when an error occurs in different threads, e.g. during plotting of data for multiple particle classes for the `Reconstruction` tab.

**Comment by merrygoat** [comment]
That seems good.
