### ISSUE TITLE
Enhancement/Fix: Position scaling in example data

### ISSUE THREAD

**Issue by dmitrypuzyrev** [ANP-Granular/ParticleTracking#95]
**Describe the bug**
In example data (.csv files), the endpoint coordinates are multiplied by 0.1 and require the parameter `Settings ->Visual Settings -> position scaling = 10` for a proper representation. At the same time, the default parameter value after the installation is `position scaling = 1`.

**To Reproduce**
1. Install the RodTracker GUI package
2. Load the default images
3. Load the default data
4. See that the rods overlays are small and concentrated in the upper left corner

**Expected behavior**
The example data should correspond to the default `position scaling` parameter value (1).

**Desktop (please complete the following information):**
Independent on the install option/OS 

<img width="1920" alt="Screenshot 2024-07-04 13 33 46" src="https://github.com/ANP-Granular/ParticleTracking/assets/15157262/3794f989-6f39-4c4c-aa45-2aae1d26703c">

**Comment by merrygoat** [comment]
Yes, this works correctly for me now.
