### ISSUE TITLE
Example data not consistent

### ISSUE THREAD

**Issue by merrygoat** [ANP-Granular/ParticleTracking#97]
In the folder RodTracker\src\RodTracker\resource\example_data\images\gp3 (and also gp4 folder) there are images 500-519 and 696 to 700.

In the folder RodTracker\src\RodTracker\resource\example_data\csv the data are for frames 500 -> 550.

I think 20 frames is good enough to get the idea of how the software works and so you could remove images 696 -> 700 and the CSV data for frames > 519.

**Comment by dmitrypuzyrev** [comment]
The excessive data were removed in the latest release, now only example images and data for frames 500-519 are present.
