### ISSUE TITLE
Unable to select folder in Linux

### ISSUE THREAD

**Issue by saipreethamsata** [ANP-Granular/ParticleTracking#99]
I am trying to select the images and data from the GUI using Linux environment. I am unable to select the corresponding folders for the images and data from the local directory using the GUI.

1. Started the Rod Tracker GUI from the terminal window
2. Selected "Load Images" and "Load Rods" buttons on the GUI
3. Unable to select the corresponding folder from the window

The corresponding folder must be selected and the images and the rod positions must be loaded

**Screenshots**
![Screenshot from 2024-08-15 14-18-57](https://github.com/user-attachments/assets/77861d12-22ef-4b87-9555-ed63f1f64889)

**Desktop :**
 - OS: Ubuntu 22.04.1 LTS
 - Python Version: 3.12.4

**Additional context**
If I manually specify the folder location for the rod images and rod data, sometimes I am able to load the image data. However the rod positions cannot be loaded still.

**Logs**
[08/15 14:14:53] RodTracker ERROR: Uncaught exception:
Traceback (most recent call last):
  File "/home/saipreetham/anaconda3/envs/RodTracker1/lib/python3.12/site-packages/RodTracker/backend/img_data.py", line 131, in select_images
    self.open_image_folder(file)
  File "/home/saipreetham/anaconda3/envs/RodTracker1/lib/python3.12/site-packages/RodTracker/backend/img_data.py", line 163, in open_image_folder
    frame = int(chosen_file.stem.split("_")[-1])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: invalid literal for int() with base 10: 'pyproject'
[08/15 14:23:41] RodTracker.ui.loggerwidget INFO: /home/saipreetham/.local/share/RodTracker/Session_7eq5791z
[08/15 14:23:41] RodTracker.backend.logger WARNING: category: default
function: None, line: 0
file: None

**Comment by a-niem** [comment]
@saipreethamsata 
The problem you described should be fixed.

**Comment by dmitrypuzyrev** [comment]
@a-niem, I have a similar problem on Ubuntu after updating to the latest commits on `develop` branch. All folders are simply inactive in the main part of "Open a folder of images" window, see the screenshot.
@saipreethamsata , does it work for you at the moment?

![image](https://github.com/user-attachments/assets/2fb2c10c-e23c-4168-8ada-db60a61352a0)

**Comment by saipreethamsata** [comment]
@dmitrypuzyrev It is not working for me still!

**Comment by a-niem** [comment]
@dmitrypuzyrev, @saipreethamsata I'm not able to reproduce your errors. Unfortunately, I don't have access to a machine with Linux as the OS at the moment and don't have time to change it for one of my computers. When testing your described problems on Ubuntu in WSL everything works as intended.

I'm afraid you will have to fix the issue yourselves this time.

I'm guessing the problem will be in `ui/dialogs.py` in the `select_data_folder()`-function or in `image_data.py` in the `select_images()`-function where the folder-selection-dialog is configured.

**Comment by dmitrypuzyrev** [comment]
@a-niem all good, we will try to fix this issue. 
Perhaps might be helpful in case it's some conflict with a file manager, which Ubuntu/nautilus version do you have in WSL?

**Comment by saipreethamsata** [comment]
It is working now! Thanks!
